### ISSUE TITLE
Project not running

### ISSUE THREAD

**Issue by diegoALCE95** [olafsulich/fullstack-nextjs-ecommerce#1]
Hi.

I followed this steps:

```
git clone https://github.com/olafsulich/fullstack-nextjs-ecommerce.git

npm install

npm run dev
```

And got this error after running npm run dev:

```
error - ./pages/_app.tsx:5:0
Module not found: Can't resolve 'next-auth/react'
  3 | import { Hydrate, QueryClient, QueryClientProvider } from 'react-query';
  4 | import { ReactQueryDevtools } from 'react-query/devtools';
> 5 | import { SessionProvider } from 'next-auth/react';
  6 | import 'tailwindcss/tailwind.css';
  7 | import { CartProvider } from '../components/cart/context/cartContext';
  8 | 
```

![image](https://user-images.githubusercontent.com/45726798/144301147-2d5ab5a0-d10a-4991-929d-d6a8959ab8d9.png)

Am I missing something? Thanks!

**Comment by olafsulich** [comment]
Hi, that's strange. I updated the "Installation" section, can you double-check that?

**Comment by Kofsaku** [comment]
it seems like I am facing the same error. I am trying to solve this.

![Screen Shot 2021-12-02 at 9 41 30](https://user-images.githubusercontent.com/51185002/144336966-29e986cb-a220-4bc5-9f6a-c3890b6ace15.png)

**Comment by diegoALCE95** [comment]
> Hi, that's strange. I updated the "Installation" section, can you double-check that?

Oh no I didn't, silly me, that must be the issue.

**Comment by olafsulich** [comment]
Let me know when you solve it :)

**Comment by olafsulich** [comment]
Seems outdated, let me know if you struggle with this issue now
